# This is a TOML document. See https://toml.io/

# It is a configuration file for trpbe at TODO

title = "Initial trbpe configuation file - Mike Stitt's fork"

[env]
add_to_env = [
    { RPYBUILD_PARALLEL = "1" },
    { RPYBUILD_CC_LAUNCHER  = "ccache" },
    { GCC_COLORS = "1" },
]

[robotpyrepos]
mostRobotPyRepo.name = 'mostrobotpy'
mostRobotPyRepo.url = 'git@github.com:MikeStitt/mostrobotpy.git'
mostRobotPyRepo.branch = 'pyIterativeAndTimedRobot'

mostRobotPyAddRepos = [
    {name='robotpy-rev', url='https://github.com/robotpy/robotpy-rev', branch='main'},
    #{name='robotpy-navx', url='https://github.com/robotpy/robotpy-navx', branch='main'},
]

addFullRobotRepos = [
    {name='mostRobotPySpires2025', url='git@github.com:spiresfrc9106/spiresRobot2025.git', branch='exp-timedrobotpy'},
    #{name='robotpy-navx', url='https://github.com/robotpy/robotpy-navx', branch='main'},
]

