# autogenerated by 'robotpy-build create-imports timedrobotmath timedrobotmath._rpydemo'
from ._timedrobotmath import getSizeOfLong, cppCalcFutureExpirationUs

__all__ = ["getSizeOfLong", "cppCalcFutureExpirationUs"]
